### ISSUE TITLE
Inline tags

### ISSUE THREAD

**Issue by Codemaine** [JaleelB/emblor#29]
Add the ability for the tags to appear in the input field, similar to the image attached below

![image](https://github.com/JaleelB/emblor/assets/64845752/479b15b2-08ff-4efd-81e5-5e71117c6c12)

**Comment by Codemaine** [comment]
@JaleelB I would like to know if this is being worked on, and if there's an ETA. Thanks

**Comment by JaleelB** [comment]
> @JaleelB I would like to know if this is being worked on, and if there's an ETA. Thanks

@Codemaine yes, this will be worked on

**Comment by zahidiqbalnbs** [comment]
@JaleelB thanks for the amazing hard work. Can you please let me know when do you think you will be able to complete the inline tags feature roughly. Thanks in advance!

**Comment by JaleelB** [comment]
https://github.com/JaleelB/emblor/assets/78449846/0133cedc-6fdc-4a38-91d4-e2f2ec3cc80a

@Codemaine @zahidiqbalnbs The feature is complete and has been deployed. Update to the latest version of the package to try it out or visit the docs site to play around with the demo: https://emblor.jaleelbennett.com/api-reference

**Comment by JaleelB** [comment]
The feature to render tags inside the input field has been successfully implemented and merged. This issue will now be closed

**Comment by zahidiqbalnbs** [comment]
@JaleelB that was a real quick. I have checked the amazing demo and yes everything looks great!! I'll be for sure using this, just one handy feature I can think of right now is if we press backspace in the input field that should have removed the last tag and so on, what do you say? May be one additional prop removeOnBackspace: boolean

**Comment by zahidiqbalnbs** [comment]
@JaleelB: I created this [issue](https://github.com/JaleelB/emblor/issues/41), I am unable to add feature and enhancement label. Please add those. Thank you for your support and hard work.
