### ISSUE TITLE
AutoComplete inside a Popover

### ISSUE THREAD

**Issue by asaf** [JaleelB/emblor#32]
When autoComplete is enabled, I suggest making it possible to render the possible options inside a popover to avoid allocating too much screen space for this component.

Such as the _Status_ dropdown filter in https://ui.shadcn.com/examples/tasks

**Comment by kavinda1995** [comment]
+1 to this. Not having a popover makes this library a no-go for mobile devices

**Comment by JaleelB** [comment]
https://github.com/JaleelB/emblor/assets/78449846/109d251c-12a8-4307-b70a-14dc5aa2b2ab

@asaf This is something you can already do by passing the usePopoverForTags boolean. See the general properties under the API reference page: https://emblor.jaleelbennett.com/api-reference

**Comment by asaf** [comment]
But the list of all possible tags is always opened and with static 10 elements.

**Comment by JaleelB** [comment]
> Isn't it only shows the entered tags? @JaleelB

@kavinda1995 Yes, the popover shows the entered tags to prevent them from causing a long tag list which could possibly cause layout shifts. Regarding the possible options, I will work on a feature to toggle showing it list on focus or something. I misunderstood the original comment

**Comment by asaf** [comment]
I think it make sense, it can shrink down into a sort of a selectbox to avoid taking large portion of the screen :)
this is somewhat relevant to https://github.com/JaleelB/emblor/issues/29

**Comment by JaleelB** [comment]
@asaf  @kavinda1995  
The enhancements discussed in this thread have been addressed in the [v1.2.0 release](https://github.com/JaleelB/emblor/releases/tag/emblor%401.2.0). 

### Key Improvements:
- Integrated a popover for autocomplete list options to optimize screen space usage.
- Added checkbox indicators for selected autocomplete items.
- Ensured inputs remain editable when the popover is open.
- Respected user-defined `onBlur` and `onFocus` events.

Thank you for your feedback! Feel free to test the new version and provide further feedback if needed.
