### ISSUE TITLE
Feature request: Keyboard Interactions

### ISSUE THREAD

**Issue by Thesmit113** [JaleelB/emblor#38]
Add Keyboard Interactions such as delete, backspace ....
for reference : https://www.radix-vue.com/components/tags-input#keyboard-interactions

you can see implementations in shadcn-vue : https://www.shadcn-vue.com/docs/components/tags-input

**Comment by JaleelB** [comment]
@Thesmit113 
The enhancements discussed in this thread have been addressed in the [v1.3.0 release](https://github.com/JaleelB/emblor/releases/tag/emblor%401.3.0).

Key Improvements:
- Added state management for active tag index
- Implemented keyboard navigation for tag input
- Integrated keyboard navigation support with custom tags
- Improved focus management to enhance accessibility
- Added visual indicators for active tags

Thank you for your feedback! Feel free to test the new version and provide further feedback if needed.
