### ISSUE TITLE
Inline tags - Remove tag when backspace key pressed

### ISSUE THREAD

**Issue by zahidiqbalnbs** [JaleelB/emblor#41]
@JaleelB : One handy feature I can think of right now is if we press backspace in the input field that should have removed the last tag and so on, what do you say? May be one additional prop removeOnBackspace: boolean will do the trick.

Thank you!

**Comment by JaleelB** [comment]
@zahidiqbalnbs 
The enhancements discussed in this thread have been addressed in the [v1.3.0 release](https://github.com/JaleelB/emblor/releases/tag/emblor%401.3.0).

See issue https://github.com/JaleelB/emblor/issues/38
