### ISSUE TITLE
Inline tags show horizontal in input

### ISSUE THREAD

**Issue by Codemaine** [JaleelB/emblor#45]
You recently implemented the inline tags (which look awesome), but it would be best, if there was an option to have the tags show horizontally in the input, like the image attached. Thanks :)

![image](https://github.com/JaleelB/emblor/assets/64845752/d9ba13c6-c258-4a87-afc2-f154eec51cbc)

**Comment by JaleelB** [comment]
@Codemaine  Let me know if I am missing something, but it works like this now. 

<img width="952" alt="Screenshot 2024-05-30 at 2 25 29 PM" src="https://github.com/JaleelB/emblor/assets/78449846/32acbdb3-761d-425b-ab10-aa85dbf128e3">

**Comment by Codemaine** [comment]
This is how it shows on my implementation

<img width="381" alt="image" src="https://github.com/JaleelB/emblor/assets/64845752/dc98a739-5de0-40de-b17a-145605079204">

**Comment by Codemaine** [comment]
Shows the same on the documentation

<img width="940" alt="image" src="https://github.com/JaleelB/emblor/assets/64845752/dfdfd2d1-02da-40d9-8b74-ac6894ac512d">

**Comment by JaleelB** [comment]
> This is how it shows on my implementation
> 
> <img alt="image" width="381" src="https://private-user-images.githubusercontent.com/64845752/335345053-dc98a739-5de0-40de-b17a-145605079204.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwOTU4NjYsIm5iZiI6MTcxNzA5NTU2NiwicGF0aCI6Ii82NDg0NTc1Mi8zMzUzNDUwNTMtZGM5OGE3MzktNWRlMC00MGRlLWIxN2EtMTQ1NjA1MDc5MjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDE4NTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YzM3NmJjNjM1YjA5M2QwMGM1Y2U5Y2VkYjg3ZDgyNDUxNjVlYjk4YzAyNTA4ZGQ3YTdmNWI4MzBjN2RmYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pyLTe_Qpbu1EDuOBIqUW7cB61P39lpWnQITaJ-J5Db4">

@Codemaine That is how it should be. You've set a width some where on the input (maybe on the parent container). If the space left in the container is less than the width of the input, the input wraps to a new line. The same logic applies to the tags as well. They wrap inside the tag list.

Other implementations of tag inputs with inline tags work the same way. Here is an example: https://mantine.dev/core/tags-input/

**Comment by Codemaine** [comment]
Yea, I'm aware that it's supposed to wrap when there's no available horizontal space, that's why I'm requesting for this. You should allow the user to scroll horizontally to view the tags, to keep the input's height constant.

**Comment by JaleelB** [comment]
Ah, I see. You didn't make that clear in your initial comment. This isn't exactly a default behavior for tag inputs so I'll have to test this out to see if it's a good fit.
