### ISSUE TITLE
Closing of Tag Popover when clicking outside

### ISSUE THREAD

**Issue by Ricardosgeral** [JaleelB/emblor#55]
Hi,
Great component.

I just can'd to figure out how to close the Tag Popover when clicking outside the selection box. Do you know how to achiev it?

For example, in the first example in https://emblor.jaleelbennett.com/api-reference it is only possible to close the popover by clicking the down arrow, which is anoying and not very user friendly.

I think it migh be missing adding the PopoverClose from Radix UI library. This is suggested in https://stackoverflow.com/questions/77144813/how-to-close-radix-shadcn-popover-from-inside-of-it

thank out

**Comment by JaleelB** [comment]
@Ricardosgeral 

The enhancements discussed in this thread have been addressed in the [v1.3.6 release](https://github.com/JaleelB/emblor/releases/tag/emblor%401.3.6).

**Comment by Ricardosgeral** [comment]
great, it's working now as expected.
Ricardo Santos
