### ISSUE TITLE
Backspace Not remove character. Please Help.

### ISSUE THREAD

**Issue by webservice96** [JaleelB/emblor#62]
Check the images.

![image](https://github.com/JaleelB/emblor/assets/35348437/17570fcd-b52e-4d4c-8c13-0ecda445571d)
![image](https://github.com/JaleelB/emblor/assets/35348437/a5178ca9-1822-44f0-b8d9-3dd7044ba2dc)
![image](https://github.com/JaleelB/emblor/assets/35348437/fd39daaa-3ebb-405f-aaf9-6f4d7c8c7582)

**Comment by webservice96** [comment]
The Problem is in the latest version. The 1.0.3 version is working fine. Please fix that issue on the latest version. I'm using in next.

**Comment by JaleelB** [comment]
@webservice96 Please be more descriptive of the problem. From what I can gather you're saying using backspace to delete a character in the input didn't work?

Additionally, I would recommend upgrading from version 1.0.3. Subsequent releases fixed some issue that this version introduced

**Comment by rangwea** [comment]
I have the same proble.
<img width="1507" alt="image" src="https://github.com/user-attachments/assets/6516ca08-d3e2-4f24-baf4-4a682afb403f">

**Comment by rangwea** [comment]
I know why happened this problem, you need add this properties:
![image](https://github.com/user-attachments/assets/2e96dd9e-07cc-49c5-93b7-d1a76af8e610)

**Comment by JaleelB** [comment]
> I know why happened this problem, you need add this properties: ![image](https://private-user-images.githubusercontent.com/12287570/348584950-2e96dd9e-07cc-49c5-93b7-d1a76af8e610.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NzE0MjksIm5iZiI6MTcyMTY3MTEyOSwicGF0aCI6Ii8xMjI4NzU3MC8zNDg1ODQ5NTAtMmU5NmRkOWUtMDdjYy00OWM1LTkzYjctZDFhNzZhZjhlNjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDE3NTg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MjBjYmE0M2FhMWNkZDg5MWE5OGM3NDlhOTFhNDhlOGY4MTE3MTEwNGQ3M2JiY2IyMmZhY2E0NWUyNTBlMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jjnL_B2bs_mrdZEtyIYORVw1R5vfeLn2IUR0tZ--xYg)

@rangwea Yes, you need to handle the active tag index management externally—the code examples for each input demo reference this. I'll add a not in the documentation that highlights this fact better. Is it safe to assume that managing the active tag index externally fixed your issue?

**Comment by jose-jacinto** [comment]
Not the issue creator but I had a similar problema and @rangwea suggestion worked.
I managed the indexes with
`const [activeTagIndex, setActiveTagIndex] = React.useState<number | null>(null);`
Thanks

**Comment by JaleelB** [comment]
For anyone facing this issue, visit the Keyboard Navigation page in the docs page: https://emblor.jaleelbennett.com/keyboard-interactions
