### ISSUE TITLE
[bug]: emblor showcount not working with enableAutocomplete option

### ISSUE THREAD

**Issue by asif-iqbal-munna** [JaleelB/emblor#79]
### Describe the bug

![Screenshot 2024-08-06 165818](https://github.com/user-attachments/assets/451c560b-e77a-433c-81ff-36e6861607a0)

### Here in the Autocomplete component setState function which is responsible for updating the count with "setTagCount" is not passed?

![Screenshot 2024-08-06 170113](https://github.com/user-attachments/assets/930e09e7-d652-4f7f-8f4c-b78a3307a804)
![Screenshot 2024-08-06 170436](https://github.com/user-attachments/assets/6602eae8-72c1-44d3-a974-11e7ee6e1d85)

### So when "toggleTag" function is triggered by onClick event from option that is not updating the tagCount. 

![Screenshot 2024-08-06 162412](https://github.com/user-attachments/assets/6a58554c-2659-4d44-8184-056764d3b8c1)

### For this issue when i am clicking options from the select options it's not updating the count.

![Screenshot 2024-08-06 162525](https://github.com/user-attachments/assets/4cd6ab87-12e4-4496-bbbe-5f528ecb1cb8)

### On the other hand, when i am removing those that time "setTagCount" is updating, but as is deducting count going to a minus figure. 

![Screenshot 2024-08-06 162819](https://github.com/user-attachments/assets/71d4de6a-5259-4999-932a-1e9e3a3bc528)

### How to reproduce

1. import { TagInput } from 'emblor'
2. Pass showCount and enableAutocomplete options as true

### Link to reproduction

https://github.com/JaleelB/emblor/tree/main

**Comment by JaleelB** [comment]
https://github.com/user-attachments/assets/8920159a-da90-4596-beb7-294962e43e82

This fix was implemented. You can see the changes in the latest version of the package
