### ISSUE TITLE
[feat]: Allow keyboard ↑↓ to select autocomplete suggestion

### ISSUE THREAD

**Issue by nawok** [JaleelB/emblor#80]
### Feature description

Currently, when working with the autocomplete variant, the user needs to use their mouse to select a suggestion.

It would be nice to be able to `↑↓` between them.

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by JaleelB** [comment]
https://github.com/user-attachments/assets/b96af1e3-6358-48b3-ae4a-6f6879a67176

This feature was added. To activate keyboard navigation for the autocomplete dropdown, focus the input while the dropdown is open and use the up and down keys to ↑↓ between them. Pressing enter toggles the autocomplete options
