### ISSUE TITLE
[feat]:  upgrade dep 'tailwind-merge'

### ISSUE THREAD

**Issue by flipvh** [JaleelB/emblor#82]
### Feature description

Upgrade dep tailwind-merge from 1.14.0 to v2. Or perhaps there is a way to remove the dependency? It best to have as little dependencies for these kinds of libraries, I guess. Thanks!

### Additional Context

I am not 100% sure but my project seems to both have  tailwind-merge v1 and v2 in its bundle. I think this might be related to emblor dependency still running on v1. Can you perhaps upgrade tailwind-merge to v2?  [https://github.com/dcastil/tailwind-merge](https://github.com/dcastil/tailwind-merge) Thnks!

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by JaleelB** [comment]
This fix has been implemented in the latest version of the package
